[package]
name = "model_voxelization"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
bevy_egui = "0.33.0"
rfd = "0.15.3"
tobj = "4.0.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
